"""empty message

Revision ID: 14699178e17a
Revises: e5d5ebdd0831
Create Date: 2019-01-06 13:32:57.618216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14699178e17a'
down_revision = 'e5d5ebdd0831'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('investigation', sa.Column('afb', sa.Unicode(), nullable=True))
    op.add_column('investigation', sa.Column('albumin', sa.Float(), nullable=True))
    op.add_column('investigation', sa.Column('alp', sa.Float(), nullable=True))
    op.add_column('investigation', sa.Column('alt', sa.Float(), nullable=True))
    op.add_column('investigation', sa.Column('ast', sa.Float(), nullable=True))
    op.add_column('investigation', sa.Column('bun', sa.Float(), nullable=True))
    op.add_column('investigation', sa.Column('ca', sa.Float(), nullable=True))
    op.add_column('investigation', sa.Column('chol', sa.Integer(), nullable=True))
    op.add_column('investigation', sa.Column('cl', sa.Float(), nullable=True))
    op.add_column('investigation', sa.Column('cr', sa.Float(), nullable=True))
    op.add_column('investigation', sa.Column('cryptoAgBlood', sa.Unicode(), nullable=True))
    op.add_column('investigation', sa.Column('cryptoAgCSF', sa.Unicode(), nullable=True))
    op.add_column('investigation', sa.Column('direct_bilirubin', sa.Float(), nullable=True))
    op.add_column('investigation', sa.Column('dst', sa.ARRAY(sa.Unicode()), nullable=True))
    op.add_column('investigation', sa.Column('fbs', sa.Integer(), nullable=True))
    op.add_column('investigation', sa.Column('geneXpert', sa.Unicode(), nullable=True))
    op.add_column('investigation', sa.Column('globulin', sa.Float(), nullable=True))
    op.add_column('investigation', sa.Column('hb', sa.Float(), nullable=True))
    op.add_column('investigation', sa.Column('hba1c', sa.Float(), nullable=True))
    op.add_column('investigation', sa.Column('hco3', sa.Float(), nullable=True))
    op.add_column('investigation', sa.Column('hct', sa.Float(), nullable=True))
    op.add_column('investigation', sa.Column('hdl', sa.Integer(), nullable=True))
    op.add_column('investigation', sa.Column('hivMutation', sa.ARRAY(sa.Unicode()), nullable=True))
    op.add_column('investigation', sa.Column('hivResistance', sa.ARRAY(sa.Unicode()), nullable=True))
    op.add_column('investigation', sa.Column('k', sa.Float(), nullable=True))
    op.add_column('investigation', sa.Column('ldl', sa.Integer(), nullable=True))
    op.add_column('investigation', sa.Column('lineProbeAssay', sa.Unicode(), nullable=True))
    op.add_column('investigation', sa.Column('mg', sa.Float(), nullable=True))
    op.add_column('investigation', sa.Column('na', sa.Float(), nullable=True))
    op.add_column('investigation', sa.Column('po4', sa.Float(), nullable=True))
    op.add_column('investigation', sa.Column('sputumCulture', sa.Unicode(), nullable=True))
    op.add_column('investigation', sa.Column('tg', sa.Integer(), nullable=True))
    op.add_column('investigation', sa.Column('total_bilirubin', sa.Float(), nullable=True))
    op.add_column('investigation', sa.Column('total_prot', sa.Float(), nullable=True))
    op.add_column('investigation', sa.Column('tpha', sa.Unicode(), nullable=True))
    op.add_column('investigation', sa.Column('urine_cr', sa.Float(), nullable=True))
    op.add_column('investigation', sa.Column('urine_glucose', sa.Float(), nullable=True))
    op.add_column('investigation', sa.Column('urine_glucose_dipstick', sa.Float(), nullable=True))
    op.add_column('investigation', sa.Column('urine_prot', sa.Float(), nullable=True))
    op.add_column('investigation', sa.Column('urine_prot_dipstick', sa.Float(), nullable=True))
    op.add_column('investigation', sa.Column('wbc', sa.Float(), nullable=True))
    op.add_column('investigation', sa.Column('wbcPBasos', sa.Float(), nullable=True))
    op.add_column('investigation', sa.Column('wbcPEos', sa.Float(), nullable=True))
    op.add_column('investigation', sa.Column('wbcPLym', sa.Float(), nullable=True))
    op.add_column('investigation', sa.Column('wbcPNeu', sa.Float(), nullable=True))
    op.alter_column('investigation', 'date',
               existing_type=sa.DATE(),
               nullable=False)
    op.drop_column('investigation', 'hivResistence')
    op.drop_column('investigation', 'tb')
    op.add_column('visit', sa.Column('whySwitch', sa.Unicode(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('visit', 'whySwitch')
    op.add_column('investigation', sa.Column('tb', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('investigation', sa.Column('hivResistence', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('investigation', 'date',
               existing_type=sa.DATE(),
               nullable=True)
    op.drop_column('investigation', 'wbcPNeu')
    op.drop_column('investigation', 'wbcPLym')
    op.drop_column('investigation', 'wbcPEos')
    op.drop_column('investigation', 'wbcPBasos')
    op.drop_column('investigation', 'wbc')
    op.drop_column('investigation', 'urine_prot_dipstick')
    op.drop_column('investigation', 'urine_prot')
    op.drop_column('investigation', 'urine_glucose_dipstick')
    op.drop_column('investigation', 'urine_glucose')
    op.drop_column('investigation', 'urine_cr')
    op.drop_column('investigation', 'tpha')
    op.drop_column('investigation', 'total_prot')
    op.drop_column('investigation', 'total_bilirubin')
    op.drop_column('investigation', 'tg')
    op.drop_column('investigation', 'sputumCulture')
    op.drop_column('investigation', 'po4')
    op.drop_column('investigation', 'na')
    op.drop_column('investigation', 'mg')
    op.drop_column('investigation', 'lineProbeAssay')
    op.drop_column('investigation', 'ldl')
    op.drop_column('investigation', 'k')
    op.drop_column('investigation', 'hivResistance')
    op.drop_column('investigation', 'hivMutation')
    op.drop_column('investigation', 'hdl')
    op.drop_column('investigation', 'hct')
    op.drop_column('investigation', 'hco3')
    op.drop_column('investigation', 'hba1c')
    op.drop_column('investigation', 'hb')
    op.drop_column('investigation', 'globulin')
    op.drop_column('investigation', 'geneXpert')
    op.drop_column('investigation', 'fbs')
    op.drop_column('investigation', 'dst')
    op.drop_column('investigation', 'direct_bilirubin')
    op.drop_column('investigation', 'cryptoAgCSF')
    op.drop_column('investigation', 'cryptoAgBlood')
    op.drop_column('investigation', 'cr')
    op.drop_column('investigation', 'cl')
    op.drop_column('investigation', 'chol')
    op.drop_column('investigation', 'ca')
    op.drop_column('investigation', 'bun')
    op.drop_column('investigation', 'ast')
    op.drop_column('investigation', 'alt')
    op.drop_column('investigation', 'alp')
    op.drop_column('investigation', 'albumin')
    op.drop_column('investigation', 'afb')
    # ### end Alembic commands ###
