"""empty message

Revision ID: 276706929ea4
Revises: 78d92a1c712c
Create Date: 2019-07-16 18:11:05.918189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '276706929ea4'
down_revision = '78d92a1c712c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patient', sa.Column('care', sa.Unicode(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patient', 'care')
    # ### end Alembic commands ###
