"""empty message

Revision ID: 310f902d3652
Revises: e6cddc4d8f0f
Create Date: 2019-01-21 10:03:33.657988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '310f902d3652'
down_revision = 'e6cddc4d8f0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patient', sa.Column('patientStatus', sa.Unicode(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patient', 'patientStatus')
    # ### end Alembic commands ###
