"""empty message

Revision ID: 82bb4ec85fb5
Revises: 310f902d3652
Create Date: 2019-01-22 22:39:08.270158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82bb4ec85fb5'
down_revision = '310f902d3652'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patient', sa.Column('referOutTo', sa.Unicode(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patient', 'referOutTo')
    # ### end Alembic commands ###
