"""empty message

Revision ID: c6482e16faf5
Revises: 276706929ea4
Create Date: 2019-07-19 18:57:05.905440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6482e16faf5'
down_revision = '276706929ea4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patient', sa.Column('cares', sa.Unicode(), nullable=True))
    op.drop_column('patient', 'care')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patient', sa.Column('care', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('patient', 'cares')
    # ### end Alembic commands ###
