"""empty message

Revision ID: e5d5ebdd0831
Revises: 1db068f580b4
Create Date: 2018-12-10 13:07:57.463645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5d5ebdd0831'
down_revision = '1db068f580b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('investigation', sa.Column('hivResistence', sa.Unicode(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('investigation', 'hivResistence')
    # ### end Alembic commands ###
