"""empty message

Revision ID: e6cddc4d8f0f
Revises: 14699178e17a
Create Date: 2019-01-20 02:07:27.379875

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e6cddc4d8f0f'
down_revision = '14699178e17a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('investigation', sa.Column('urine_prot_cr_ratio', sa.Float(), nullable=True))
    op.add_column('investigation', sa.Column('wbcPMono', sa.Float(), nullable=True))
    op.drop_column('investigation', 'urine_prot')
    op.drop_column('investigation', 'urine_cr')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('investigation', sa.Column('urine_cr', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('investigation', sa.Column('urine_prot', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('investigation', 'wbcPMono')
    op.drop_column('investigation', 'urine_prot_cr_ratio')
    # ### end Alembic commands ###
