"""empty message

Revision ID: f57cf7ce230b
Revises: 82bb4ec85fb5
Create Date: 2019-01-26 12:27:53.850411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f57cf7ce230b'
down_revision = '82bb4ec85fb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'patient', ['cid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'patient', type_='unique')
    # ### end Alembic commands ###
